<?php
/**
 * The sidebar containing the main widget area
 *
 * If no active widgets are in the sidebar, hide it completely.
 *
 * @package WordPress
 * @subpackage Twenty_Twelve
 * @since Twenty Twelve 1.0
 */
?>

	<?php if ( is_active_sidebar( 'sidebar-1' ) ) : ?>
		<div id="secondary" class="widget-area" role="complementary">
			<a href="http://www.doctoranavarrete.cl/contacto/"><img style="border-radius: 3px; box-shadow: 0 1px 4px rgba(0, 0, 0, 0.2);" src="<?php echo home_url(); ?>/wp-content/uploads/dudas-consultas.jpg"></a>
</br></br>
<style type="text/css">
.css_btn_class {
	font-size:23px;
	font-family:Arial;
	font-weight: 700;
	-moz-border-radius:8px;
	-webkit-border-radius:8px;
	border-radius:8px;
	border:1px solid #dcdcdc;
	padding:15px 37px;
	text-decoration:none;
	background:-moz-linear-gradient( center top, #5bb2bb 5%, #018A97 100% );
	background:-ms-linear-gradient( top, #5bb2bb 5%, #018A97 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#5bb2bb', endColorstr='#018A97');
	background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #5bb2bb), color-stop(100%, #018A97) );
	background-color:#5bb2bb;
	color:#f0f0f0;
	display:inline-block;
	text-shadow:1px 1px 0px #3ca2ad;
 	-webkit-box-shadow:inset 1px 1px 0px 0px #3ca2ad;
 	-moz-box-shadow:inset 1px 1px 0px 0px #3ca2ad;
 	box-shadow:inset 1px 1px 0px 0px #3ca2ad;
}
.css_btn_class:hover {
	background:-moz-linear-gradient( center top, #018A97 5%, #b5dce0 100% );
	background:-ms-linear-gradient( top, #018A97 5%, #b5dce0 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#018A97', endColorstr='#b5dce0');
	background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #018A97), color-stop(100%, #b5dce0) );
	background-color:#dfdfdf;
}
.css_btn_class:active {
	position:relative;
	top:1px;
}
.css_btn_class .fa {
	padding-right: 10px;
}
/* This css button was generated by css-button-generator.com */
</style>
<!--<a href="http://www.doctoranavarrete.cl/reserva-hora/" style="display:inline-block; width: 263px; height: 80px; box-shadow: 0 1px 4px rgba(0, 0, 0, 0.2); "><span class="fa fa-calendar"></span>Reserva ahora</a>-->
<a href="<?php echo home_url(); ?>/reserva-hora/" class="css_btn_class" onMouseOver="this.style.color='#fff'"  onMouseOut="this.style.color='#fff'"><span class="fa fa-calendar"></span>Reservar Hora</a>

		</div><!-- #secondary -->
	<?php endif; ?>